name: Build and Release

# 触发条件：标签推送或分支推送
on:
  push:
    tags:
      - 'v*'  # 标签推送，如v1.0.0
    branches:
      - '*'   # 所有分支推送

permissions:
  contents: write
  packages: write
  attestations: write
  id-token: write

jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Login to GitHub Container Registry
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine GoReleaser command
        id: goreleaser-command
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "command=release --clean" >> $GITHUB_OUTPUT
          else
            echo "command=build --clean" >> $GITHUB_OUTPUT
          fi

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: ${{ steps.goreleaser-command.outputs.command }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
